config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get "/auth/google_oauth2/callback" => "sessions#create", as: :create_session
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/profile" => "users#show", as: :profile
  get "/profile/contacts" => "users#contacts"
  get "/profile/archive" => "users#archive"

  get "/contacts/start_job" => "users#init_contacts_load"
  get "/contacts/job_status" => "users#check_on_contacts_loading"

  resources :meetings, except: :index do
    resources :invites, only: :destroy
    resources :agenda_topics, only: [:create, :update, :destroy] do
      resources :conclusions, only: [:create, :update]
      resources :votes, only: [:create, :destroy]
    end

    resources :actionables, only: [:create, :update, :destroy] do
      resources :responsibilities, only: [:create, :destroy]
    end

    get "/invited" => "meetings#check_invited"
    get "/attendees" => "meetings#attendees"
  end

  match "/meetings/:id/update_notes" => "meetings#update_notes", as: :update_notes, via: :PATCH

  match ':not_found' => 'home#index', :constraints => { :not_found => /.*/ }, via: [:get, :post]
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  has_many :invites
  has_many :invitees, through: :invites
  belongs_to :creator, class_name: "User"
  has_many :actionables
  has_many :agenda_topics

  validates :creator_id, presence: true
  validates :title, presence: true

  def self.format_timezone(timezone)
    timezone.gsub(/\s\(US & Canada\)$/, "")
  end

  def self.format_date(datetime)
    datetime.strftime('%A - %b %d, %Y')
  end

  def self.format_time(datetime)
    datetime.strftime('%-l:%M %p')
  end

  def self.show_start_datetime(datetime, timezone)
    date = self.format_date(datetime)
    time = self.format_time(datetime)
    timezone = self.format_timezone(timezone)
    "#{date} @ #{time} (#{timezone})"
  end

  def self.format_from_to_time
    datetime.strftime('%l:%M %p')
  end

  def duration_in_seconds
    self.end_time - self.start_time
  end

  def truncated_title
    return "#{title[0..13]}..." if title.length > 13
    title
  end

  def just_the_date
    start_time.strftime('%A - %b %d, %Y')
  end

  def duration_formatted
    duration_seconds = self.duration_in_seconds

    mm, ss = duration_seconds.divmod(60)
    hh, mm = mm.divmod(60)
    dd, hh = hh.divmod(24)

    output_array = [dd == 1 ? "#{dd} day, " : "#{dd} days, ", hh == 1 ? "#{hh} hour, " : "#{hh} hours, ", mm == 1 ? "#{mm} minute, " : "#{mm} minutes, ", ss == 1 ? "#{ss} second" : "#{ss} seconds"]
    output_array.reject { |measure| measure.starts_with?("0") }.join("").chomp(", ")
  end

  def self.event_hash(event)
    { 'summary' => event.title,
      'location' => event.location,
      'description' => event.invite_notes,
      'start' => { 'dateTime' => event.start_time.to_datetime.strftime("%FT%T"), 'timeZone' => event.to_google_time_zone },
      'end' => { 'dateTime' => event.end_time.to_datetime.strftime("%FT%T"), 'timeZone' => event.to_google_time_zone },
      'attendees' => event.invitees_array
    }
  end

  def invite_notes
    "#{self.description} \n\nhttp://standup-app.herokuapp.com/meetings/#{self.id}"
  end

  def invitees_array
    self.invitees.map { |invitee| { 'email' => invitee.email } }
  end

  def email_array_for_mailer
    self.invitees.map { |invitee| invitee.email } + [self.creator.email]
  end

  def self.format_params(meeting_params)
    meeting_params[:start_time] = DateTime.strptime(meeting_params[:start_time], '%m/%d/%Y %H:%M %P') if !meeting_params[:start_time].empty?
    meeting_params[:end_time] = DateTime.strptime(meeting_params[:end_time], '%m/%d/%Y %H:%M %P') if !meeting_params[:end_time].empty?
    meeting_params
  end

  def destroy_self_and_invites
    self.invites.destroy_all
    self.destroy
  end

  def empty_datetime?
    !(self.start_time && self.end_time)
  end

  def empty_title?
  	!self.title || self.title.empty? 
  end

  def close_meeting_and_send_email
    self.update(is_done: true)
    SendGridWorker.perform_async(self.id)
  end

  def to_google_time_zone
    ActiveSupport::TimeZone::MAPPING.select {|k, v| k == self.time_zone }.values.first
  end

  def self.to_rails_time_zone(time)
    ActiveSupport::TimeZone::MAPPING.select {|k, v| v == time }.keys.first
  end

  def format_to_local_time(utc_time)
    utc_time.strftime('%m/%d/%Y %I:%M %p') unless utc_time.nil?
  end

  def start
    self.update(is_live: true)
  end

  def time_from_now
    days_from_now = ((Time.now - start_time) / 86400).floor
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
	skip_before_action :require_login, only: [:show, :check_invited]
	before_filter(only: [:update, :destroy]) { |filter| filter.check_if_meeting_is_closed(params[:id]) }
	before_filter :find_meeting_by_id, only: [:show, :edit, :destroy, :update_notes]
	include ActionView::Helpers::SanitizeHelper

	def new
		@time_zone = Meeting.to_rails_time_zone(cookies["time_zone"])
		id = params[:id]
		if id
			previous_meeting = Meeting.find_by_id(id)

			unless previous_meeting
				redirect_to profile_path and return
			end

			if previous_meeting.creator == current_user || previous_meeting.invitees.include?(current_user)
				local_time = Time.now
				@meeting = previous_meeting.dup
				@meeting.invitees = previous_meeting.invitees
				day_after_meeting = previous_meeting.start_time + 86400
				start_time = day_after_meeting < local_time ? local_time : day_after_meeting
				end_time = start_time + previous_meeting.duration_in_seconds
				@meeting.assign_attributes(start_time: start_time, end_time: end_time)
			else
				@meeting = Meeting.new
			end
		else
			@meeting = Meeting.new
		end
	end

	def show
		@showing_meeting = true
		if logged_in?
			if current_user.email.downcase != @meeting.creator.email.downcase
				@invitee_emails = @meeting.invitees.pluck(:email).map(&:downcase)
				unless @invitee_emails.include?(current_user.email.downcase)
					flash[:error] = "You don't have access to this meeting."
					redirect_to profile_path
				end
			end
		else
			render :invited
		end
	end

	def attendees
		@meeting = Meeting.find(params[:meeting_id])
		@invitees = @meeting.invitees
		contact_data = @invitees.map do |invitee|
			{ full_name: invitee.full_name, email: invitee.email }
		end
		respond_to do |format|
			format.json { render json: contact_data }
		end
	end

	def check_invited
		@meeting = Meeting.find_by_id(params[:meeting_id])
		@invitee_emails = @meeting.invitees.pluck(:email).map(&:downcase)

		if @invitee_emails.include?(params[:email].downcase)
			session[:user_id] = User.find_by_email(params[:email].downcase).id
			render :show
		else
			flash[:error] = "This email address is not associated with any of this meeting's members."
			render :invited
		end
	end

	def create
		@meeting = Meeting.new(meeting_params.merge(creator: current_user))

		if @meeting.empty_datetime? || @meeting.empty_title?
			flash.now[:error] = "A meeting must have a title, start time, and end time."
			return render :new
		end

		if @meeting.save
			Invite.create_invites(current_user, params[:attendees], @meeting)
		else
			flash.now[:error] = "There was an error processing your request. Please try again."
			return render :new
		end

		response = current_user.create_event(Meeting.event_hash(@meeting))
		if google_api_call_success?(response)
			@meeting.update(calendar_event_id: response.data.id)
			redirect_to root_path, flash: { success: "Your event was successfully created." }
		else
			@meeting.destroy_self_and_invites
			flash.now[:error] = "Google was not able to create your event. Please try again."
			render :new
		end
	end

	def edit
	end

	def update
		@time_zone = @meeting.time_zone

		if params[:close]
			@meeting.close_meeting_and_send_email
			return redirect_to profile_archive_path
		end

		if params[:start]
			@meeting.start
			return redirect_to meeting_path(@meeting)
		end

		unsaved_event = @meeting.clone # we only update the db if google calendar gets updated

		response = current_user.update_event(Meeting.event_hash(unsaved_event), @meeting.calendar_event_id)
		if google_api_call_success?(response)
			@meeting.update(meeting_params)
			@meeting.invites.destroy_all
			Invite.create_invites(current_user, params[:attendees], @meeting)
			redirect_to root_path, flash: { success: "Your event was successfully edited." }
		else
			flash.now[:error] = "Google was not able to update your event. Please try again."
			render :edit
		end
	end

	def destroy
		response = current_user.delete_event(@meeting.calendar_event_id)
		if google_api_call_success?(response) || google_api_call_410(response)
			@meeting.destroy_self_and_invites
			redirect_to root_path, flash: { success: "Your event was successfully deleted." }
		else
			redirect_to root_path, flash: { error: "Google was not able to delete your event. Please try again." }
		end
	end

  def update_notes
  	if !@meeting.is_done
	    notes = params[:notes]
	    notes.strip!
	    notes.gsub!(/(<br>|<p>|<div>)/, "\n")
	    notes = strip_tags(notes)
	    notes.strip!
	    notes.gsub!(/(\n+\s*){3,}/, "\n\n")
	    @meeting.update_attributes(notes: notes)
	    render 'update_notes'
  	end
  end

	private

	def meeting_params
		Meeting.format_params(params.require(:meeting).permit(:title, :description, :location, :start_time, :end_time, :time_zone, :notes))
	end

	def find_meeting_by_id
		@meeting = Meeting.find_by_id(params[:id])
	end
end

app/views/meetings/_add_contacts.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6 form-horizontal">
  <div class="form-group">
    <div id='contacts-search' data-control="multisearch"></div>
  </div>
</div>

app/views/meetings/_invitees.html.erb
<ul id = "invitees-list">
<% if !@meeting.is_done %>
  <% @meeting.invitees.each do |invitee| %>
    <li class = "dragon-drop" id = '<%= invitee.id %>'><%= invitee.full_name_or_email %></li>
  <% end %>
    <li class = "dragon-drop" id = '<%= @meeting.creator.id %>'><%= @meeting.creator.full_name_or_email %></li>
  </ul>
<% else %>

  <% @meeting.invitees.each do |invitee| %>
    <li class = "dragon-drop-disabled" id = '<%= invitee.id %>'><%= invitee.full_name_or_email %></li>
  <% end %>
    <li class = "dragon-drop-disabled" id = '<%= @meeting.creator.id %>'><%= @meeting.creator.full_name_or_email %></li>
  </ul>

<% end %>

app/views/meetings/_meeting.html.erb
<div class='meeting-tile'>


  <div id='meeting-date'>
    <% if !meeting.is_done %>
      <% if meeting.is_live %>
        <b class='meeting-date-display'><span id='live'><%= fa_icon 'circle' %></span> Live now!</b>
      <% elsif meeting.time_from_now == 0 %>
        <b id='today' class='meeting-date-display'><%= fa_icon 'calendar' %> Today</b>
      <% elsif meeting.time_from_now > 0 %>
        <b class='meeting-date-display'><span id='past'><%= fa_icon 'exclamation-circle' %></span> Passed scheduled date</b>
      <% else %>
        <b class='meeting-date-display'><%= fa_icon 'calendar' %> <%= "About #{pluralize(meeting.time_from_now.abs, 'day')} from now" %></b>
      <% end %>
    <% else %>
      <b class='meeting-date-display'><%= fa_icon 'calendar' %> <%= meeting.just_the_date %></b>
    <% end %>
  </div>

  <span id='meeting-title'><%= link_to "#{meeting.truncated_title}", meeting_path(meeting) %></span>

  <div class='meeting-options'>
    <% if current_user == meeting.creator %>
      <% if !meeting.is_done %>
      	<span class='meeting-option-link'><%= link_to "Duplicate", new_meeting_path(id: meeting.id) %></span>
      	<span class='meeting-option-link'><%= link_to "Edit", edit_meeting_path(meeting) %></span>
      	<span class='meeting-option-link'><%= link_to "Delete", meeting_path(meeting), method: :delete %></span>
      <% else %>
        <span class='meeting-option-link'><%= link_to "Duplicate", new_meeting_path(id: meeting.id) %></span>
      <% end %>
    <% else %>
      <% if !meeting.is_done %>
      	<span class='meeting-option-link'><%= link_to "Decline Invite", meeting_invite_path(meeting, Invite.where(invitee_id: current_user.id, meeting_id: meeting.id)[0]), method: :delete %></span>
        <% else %>
          <span id="meeting-finished"><b>Closed</b></span>
      <% end %>
    <% end %>
  </div>

</div>

app/views/meetings/_meeting_form.html.erb
<div id="meeting-form">
  <%= render "underscore_templates" %>

  <%= form_for @meeting do |f| %>
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %><br>

    <%= f.text_field :location, placeholder: 'Location (optional)', class: 'form-control' %><br>

    <%= f.text_area :description, placeholder: 'Description (optional)', class: 'form-control', rows: '4' %>


    <br><br><br>
    
    <p class='information'>To add members, type in their e-mail and hit enter:</p>
    <%= render "add_contacts" %>

    <br><br><br>

    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, { default: @time_zone }, { class: "form-control" } %><br>

    <div class='wrap-center'>
      <input id='datetimepicker_start' placeholder='Start time' type='datetime' class="form-control datetime" name="meeting[start_time]" value="<%= @meeting.format_to_local_time(@meeting.start_time) %>"/>

      <span id='right-arrow'><%= fa_icon 'long-arrow-right' %></span>
      <span id='down-arrow'><%= fa_icon 'long-arrow-down' %></span>

      <input id='datetimepicker_end' placeholder='End time'  type='datetime' class="form-control datetime" name="meeting[end_time]" value="<%= @meeting.format_to_local_time(@meeting.end_time) %>"/>
    </div>

    <br><br><br>
      <p class='information'>This will integrate with your Google Calendar.</p>
    <br>

    <%= button_tag "Submit" %>
  <% end %>
</div>

app/views/meetings/_notes.html.erb
<%= simple_format(@meeting.notes.gsub(/\n/, '<br>')) %>

app/views/meetings/_timezone_select.html.erb
<select id="meeting_time_zone" name="meeting[time_zone]" class="form-control">
    <option disabled="disabled" value="">-------------</option>
    <option <%= "selected" if @meeting.time_zone == "Hawaii" %> value="Hawaii">(GMT-10:00) Hawaii</option>
    <option <%= "selected" if @meeting.time_zone == "Alaska" %> value="Alaska">(GMT-09:00) Alaska</option>
    <option <%= "selected" if @meeting.time_zone == "Pacific Time (US & Canada)" %> value="Pacific Time (US &amp; Canada)">(GMT-08:00) Pacific Time (US &amp; Canada)</option>
    <option <%= "selected" if @meeting.time_zone == "Arizona" %> value="Arizona">(GMT-07:00) Arizona</option>
    <option <%= "selected" if @meeting.time_zone == "Mountain Time (US & Canada)" %> value="Mountain Time (US &amp; Canada)">(GMT-07:00) Mountain Time (US &amp; Canada)</option>
    <option <%= "selected" if @meeting.time_zone == "Central Time (US & Canada)" %> value="Central Time (US &amp; Canada)">(GMT-06:00) Central Time (US &amp; Canada)</option>
    <option <%= "selected" if @meeting.time_zone == "Eastern Time (US & Canada)" %> value="Eastern Time (US &amp; Canada)">(GMT-05:00) Eastern Time (US &amp; Canada)</option>
    <option <%= "selected" if @meeting.time_zone == "Indiana (East)" %> value="Indiana (East)">(GMT-05:00) Indiana (East)</option>
    <option disabled="disabled" value="">-------------</option>
</select>

app/views/meetings/_underscore_templates.html.erb
<script id="multisearch" type="text/template">
   <div>
      <div class="panel panel-default">
         <div data-role="selected-list" class="panel-body">
            <input class="pull-left" data-role="input" type="text" placeholder=""/>
         </div>
      </div>

      <div data-role="picker" class="panel panel-default">
         <div class="list-group" data-role="picker-list">
         </div>
      </div>
   </div>
</script>

<script id="contact-item" type="text/template">
   <a class="list-group-item" href="#">
      <small>{{= full_name }} | ({{= email }})</small>
   </a>
</script>

<script id="selected-item" type="text/template">
   <a class="label label-default pull-left">{{ if (full_name !== email) { }}{{= full_name}} | {{ } }}{{= email }}&nbsp;&nbsp;<span class="glyphicon glyphicon-remove" data-action="remove" aria-hidden="true"></span></a>
</script>

<script id="contact-info" type="text/template">
   <div class="popover bottom fade">
     <div class="arrow"></div>
     <h3 class="popover-title">{{= full_name }}</h3>
     <div class="popover-content">

         <div class="row">
           <div class="col-lg-4 text-center"><strong>Email</strong></div>
           <div class="col-lg-8">{{= email }}</div>
         </div>

     </div>
   </div>
</script>

app/views/meetings/edit.html.erb
<h1>Editing <%= @meeting.title %></h1>

<br><br>

<%= render "meeting_form" %>

app/views/meetings/invited.html.erb
<div class='container'>

  <br><br><br>

  <h1>Meeting Invite List</h1>

  <div class='text-center'><%= link_to "Back to home page", root_path %></div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "flash #{name}" %>
  <% end %>

  <br><br><br>

  <div id='special-signin' class='text-center'>
    <%= form_tag meeting_invited_path(@meeting), method: :get do %>
      <%= text_field_tag "email", nil, { placeholder: "Email", class: 'form-control', id:'email-check-input' } %>
      <br>
      <%= button_tag "Continue to meeting", id: 'check-email' %>
    <% end %>

    <br>

    <h1>or</h1>

    <br>

    <div class='text-center' id='check-email-google'>
      <%= link_to image_tag('google.png', :onmouseover => "this.src='#{asset_path('google-hover.png')}'", :onmouseout => "this.src='#{asset_path('google.png')}'"), '/auth/google_oauth2' %>
    </div>
  </div>

</div>

app/views/meetings/new.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "flash #{name}"%>
<% end %>

<%= render "meeting_form" %>

app/views/meetings/show.html.erb
<div class = "meeting-container">

  <div class = "meeting-header <%= 'not-live' if !@meeting.is_live %>">
    <h1 id="show-meeting-header"> 
      <% if @meeting.is_live && !@meeting.is_done %>
        <%= fa_icon 'circle' %>
      <% end %>
      <%= @meeting.title %></h1>
    <div class = 'sub-header'>
      <h2><small><%= Meeting.show_start_datetime(@meeting.start_time, @meeting.time_zone) %></small></h2>
      <% if !@meeting.is_done && @meeting.is_live %>
        <%= link_to "End Meeting", meeting_path(@meeting, close: true), method: :patch, id: "end-meeting", class: 'nice-button', data: { confirm: "Ending meeting will lock editing." } %>
      <% elsif !@meeting.is_done %>
        <%= link_to "Start Meeting", meeting_path(@meeting, start: true), method: :patch, id: 'start-meeting', class: 'nice-button' %>
      <% end %>
    </div>
  </div>

  <div class = 'meeting-content'>
  <% if @meeting.is_live %>
    <div class = 'meeting-row'>
      <div class = 'meeting-column'>
        <h2>Agenda Topics</h2>
        <%= render partial: "agenda_topics/new" %>
      </div>

      <div class = 'meeting-column'>
        <h2>Action Items</h2>
        <%= render partial: "actionables/new" %>
      </div>

      <div class = 'meeting-column'>
        <h2 style = "text-align:center;">Members</h2>
        <% if @meeting.is_live %>
          <h4 class = 'info' style = "text-align:center;">Drag members to actionables to delegate responsibilities.</h4>
        <% end %>
      </div>
    </div>

    <div class = 'meeting-row'>
      <div class = 'meeting-column'>
        <div id="agendas">
          <%= render @meeting.agenda_topics.order('updated_at DESC') %>
        </div>
      </div>

      <div class = 'meeting-column'>
        <div id="actionables" >
          <%= render @meeting.actionables.order('created_at DESC') %>
        </div>
        <span id="actionables-error"></span>
      </div>

      <div class = 'meeting-column'>
        <div id = 'members-notes'>
          <div id = "invitees">
            <%= render partial: "invitees" %>
          </div>
          <% if @meeting.is_live %>
            <h3>Notes <small class = 'info'>click off to save</small></h3>
          <% end %>
          <% if !@meeting.is_done %>
            <div id = "notes" contenteditable = 'true'><%= render partial: "notes" %></div>
          <% else %>
            <div id = "notes">
              <%= render partial: "notes" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  <% else %>
    <div class = 'meeting-row'>
      <div class = 'meeting-column not-live'>
        <h2>Agenda Topics</h2>
        <%= render partial: "agenda_topics/new" %>
      </div>
    </div>
    <div class = 'meeting-row'>
      <div class = 'meeting-column not-live'>
        <div id="agendas" class = "not-live">
          <%= render @meeting.agenda_topics.order('updated_at DESC') %>
        </div>
      </div>
    </div>
  <% end %>
  </div>

  <% if !@meeting.is_done %>
    <%= subscribe_to "/meetings/#{@meeting.id}" %>
  <% end %>

  <span id="meeting-id"><%= @meeting.id %></span>
</div>

app/views/meetings/update_notes.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  $("#notes").html("<%= j render 'meetings/notes' %>")
<% end %>