config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get "/auth/google_oauth2/callback" => "sessions#create", as: :create_session
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/profile" => "users#show", as: :profile
  get "/profile/contacts" => "users#contacts"
  get "/profile/archive" => "users#archive"

  get "/contacts/start_job" => "users#init_contacts_load"
  get "/contacts/job_status" => "users#check_on_contacts_loading"

  resources :meetings, except: :index do
    resources :invites, only: :destroy
    resources :agenda_topics, only: [:create, :update, :destroy] do
      resources :conclusions, only: [:create, :update]
      resources :votes, only: [:create, :destroy]
    end

    resources :actionables, only: [:create, :update, :destroy] do
      resources :responsibilities, only: [:create, :destroy]
    end

    get "/invited" => "meetings#check_invited"
    get "/attendees" => "meetings#attendees"
  end

  match "/meetings/:id/update_notes" => "meetings#update_notes", as: :update_notes, via: :PATCH

  match ':not_found' => 'home#index', :constraints => { :not_found => /.*/ }, via: [:get, :post]
end

app/models/actionable.rb
class Actionable < ActiveRecord::Base
  has_many :responsibilities
  has_many :responsible_users, through: :responsibilities, source: :user

  belongs_to :creator, class_name: "User"

  belongs_to :meeting

  validates :content, :meeting_id, :creator_id, presence: true
end

app/controllers/actionables_controller.rb
class ActionablesController < ApplicationController
  before_filter { |filter| filter.check_if_meeting_is_closed(params[:meeting_id]) }

  def create
    @actionable = Actionable.create(content: params[:actionable][:content], creator: current_user, meeting_id: params[:meeting_id])
  end

  def update
    @actionable = Actionable.find_by_id(params[:id]) 
    @actionable.update_attributes(content: params[:content])
  end

  def destroy
    @actionable = Actionable.find_by_id(params[:id])
    @actionable.destroy
  end
end

app/views/actionables/_actionable.html.erb
<div class = "actionable" id = "<%= actionable.id %>">
  <div class = 'meeting-item-header'>
    <% if !actionable.meeting.is_done %>
      <span class="placeholder">Drag members to assign</span>
      <%= link_to((fa_icon 'times lg'), meeting_actionable_path(actionable.meeting, actionable), class: "delete_actionable", method: :delete, remote: true, data: {confirm: "Are you sure you want to delete?"}) %>
    <% end %>
  </div>
  <% if !actionable.meeting.is_done %>
    <div class = "editable" contenteditable = 'true'><%= actionable.content %></div>
  <% else %>
    <div class = "editable"><%= actionable.content %></div>
  <% end %>
  <ul class = "responsible-users-list">
    <%= render actionable.responsible_users, actionable: actionable %>
  </ul>

</div>

app/views/actionables/_new.html.erb
<% if !@meeting.is_done %>
  <%= form_for [@meeting, Actionable.new], remote: true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "Add" %>
  <% end %> 
<% end %>

app/views/actionables/create.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  var el = $("<%= j render(@actionable)%>");
  makeDroppable(el);
  el.prependTo("#actionables");
<% end %>
$('#actionable_content').val('');

app/views/actionables/destroy.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  $('#<%= @actionable.id %>.actionable').fadeOut(200, function() {
    $(this).remove()});
<% end %>

app/views/actionables/update.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  var el = $("<%= j render(@actionable)%>");
  makeDroppable(el);
  $('#<%= @actionable.id %>.actionable').replaceWith(el);
<% end %>