config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get "/auth/google_oauth2/callback" => "sessions#create", as: :create_session
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/profile" => "users#show", as: :profile
  get "/profile/contacts" => "users#contacts"
  get "/profile/archive" => "users#archive"

  get "/contacts/start_job" => "users#init_contacts_load"
  get "/contacts/job_status" => "users#check_on_contacts_loading"

  resources :meetings, except: :index do
    resources :invites, only: :destroy
    resources :agenda_topics, only: [:create, :update, :destroy] do
      resources :conclusions, only: [:create, :update]
      resources :votes, only: [:create, :destroy]
    end

    resources :actionables, only: [:create, :update, :destroy] do
      resources :responsibilities, only: [:create, :destroy]
    end

    get "/invited" => "meetings#check_invited"
    get "/attendees" => "meetings#attendees"
  end

  match "/meetings/:id/update_notes" => "meetings#update_notes", as: :update_notes, via: :PATCH

  match ':not_found' => 'home#index', :constraints => { :not_found => /.*/ }, via: [:get, :post]
end

app/models/agenda_topic.rb
class AgendaTopic < ActiveRecord::Base
  belongs_to :creator, class_name: "User"

  has_many :votes

  belongs_to :meeting

  has_one :conclusion

  validates :content, :meeting_id, :creator_id, presence: true
end

app/controllers/agenda_topics_controller.rb
class AgendaTopicsController < ApplicationController
  before_filter { |filter| filter.check_if_meeting_is_closed(params[:meeting_id]) }

  def create
    @agenda_topic = AgendaTopic.new(meeting_id: @meeting.id, content: params[:agenda_topic][:content], creator: current_user)
    @agenda_topic.save

    respond_to do |format|
      format.html { redirect_to meeting_path(@meeting) }
      format.js
    end  
  end

  def destroy
    @agenda_topic = AgendaTopic.find_by_id(params[:id])
    @agenda_topic.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to meeting_path(@meeting) }
    end      
  end

  def update
    p @meeting
    @agenda_topic = AgendaTopic.find_by_id(params[:id])
    @agenda_topic.update(content: params[:content])

    respond_to do |format|
      format.js
      format.html { redirect_to meeting_path(@meeting) }
    end       
  end
end

app/views/agenda_topics/_agenda_topic.html.erb
<div id="<%= agenda_topic.id %>" class='agenda'>

  <div class = "meeting-item-header">

    <%= image_tag("#{agenda_topic.creator.image_path}", class: "google-circle-sm") %>
    <span class='name-tag'><%= agenda_topic.creator.full_name_or_email %></span>

    <% if !agenda_topic.meeting.is_done %>
      <%= link_to (fa_icon 'times lg'), meeting_agenda_topic_path(agenda_topic.meeting, agenda_topic), method: :delete, remote: true, data: { confirm: "Are you sure you want to delete?" } %>
    <% end %>
    <span class = 'vote'>
      <% if !agenda_topic.meeting.is_done %>
        <% if (vote = Vote.find_by(agenda_topic_id: agenda_topic, voter: current_user)) %>
          <%= link_to (fa_icon 'thumbs-up lg'), meeting_agenda_topic_vote_path(agenda_topic.meeting, agenda_topic, vote), remote: true, method: :delete, class: 'voted' %>
        <% else %>
          <%= link_to (fa_icon 'thumbs-up lg'), meeting_agenda_topic_votes_path(agenda_topic.meeting, agenda_topic), remote: true, method: :post %>
        <% end %>
      <% else %>
        <span> <%= fa_icon 'thumbs-up lg' %></span>      
      <% end %>
      <span id="vote"><%= agenda_topic.votes.count %></span>
    <span>
  </div>

  <% if !agenda_topic.meeting.is_done %>
    <div class='content'><div class='editable edit_agenda' contenteditable='true'><%= agenda_topic.content %></div></div>
  <% else %>
    <div class='content'><div class = 'editable edit_agenda'><%= agenda_topic.content %></div></div>
  <% end %>
  <div class = "agenda-bottom-border"></div>
  <% if @meeting.is_live %>
    <% if !agenda_topic.conclusion && !agenda_topic.meeting.is_done %>
      <%= link_to "What was decided?", meeting_agenda_topic_conclusions_path(agenda_topic.meeting, agenda_topic), remote: true, method: :post, class: "add_conclusion" %>
    <% elsif agenda_topic.conclusion %>
      <%= render partial: "conclusions/conclusion", locals: {conclusion: agenda_topic.conclusion}%>
    <% end %>
  <% end %>

</div>

app/views/agenda_topics/_new.html.erb
<% if !@meeting.is_done %>
  <%= form_for [@meeting, AgendaTopic.new], remote: true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "Add" %>
  <% end %>
<% end %>

app/views/agenda_topics/create.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  $('<%= escape_javascript render(@agenda_topic) %>').fadeIn().prependTo('#agendas')
<% end %>
$('#agenda_topic_content').val('')

app/views/agenda_topics/destroy.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  $("#<%= @agenda_topic.id %>.agenda").fadeOut(200, function() {
    $(this).remove()});
<% end %>

app/views/agenda_topics/update.js.erb
<% publish_to "/meetings/#{@meeting.id}" do %>
  $('#<%= @agenda_topic.id %>.agenda').replaceWith('<%= j render(@agenda_topic) %>')
<% end %>