config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get "/auth/google_oauth2/callback" => "sessions#create", as: :create_session
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/profile" => "users#show", as: :profile
  get "/profile/contacts" => "users#contacts"
  get "/profile/archive" => "users#archive"

  get "/contacts/start_job" => "users#init_contacts_load"
  get "/contacts/job_status" => "users#check_on_contacts_loading"

  resources :meetings, except: :index do
    resources :invites, only: :destroy
    resources :agenda_topics, only: [:create, :update, :destroy] do
      resources :conclusions, only: [:create, :update]
      resources :votes, only: [:create, :destroy]
    end

    resources :actionables, only: [:create, :update, :destroy] do
      resources :responsibilities, only: [:create, :destroy]
    end

    get "/invited" => "meetings#check_invited"
    get "/attendees" => "meetings#attendees"
  end

  match "/meetings/:id/update_notes" => "meetings#update_notes", as: :update_notes, via: :PATCH

  match ':not_found' => 'home#index', :constraints => { :not_found => /.*/ }, via: [:get, :post]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Standup</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class = "<%= 'meeting-body' if @showing_meeting %>" >
<% if logged_in? %>
  <header>
    <div class='container'>
      <a href="<%= profile_path %>" id='standup'>Standup</a>
      <span id='nav-bar'>
        <% if current_user.image_path %>
          <%= link_to (image_tag current_user.image_path, id: 'header-google-img'), profile_path %>
        <% end %>
        <%= link_to "Meetings", profile_path %>
        <%= link_to "Archive", profile_archive_path %>
        <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </header>
<% end %>

<%= yield %>

</body>
</html>